" vsvim specific settings for visual studio 2022
let mapleader="\<space>"

set clipboard=unnamed " yank to system clipboard
set ignorecase " ignorecase for search
set smartcase " case sensitive if uppercase is used
set number
set hlsearch

" window management
map <Leader>sx :vsc Window.CloseDocumentWindow<CR>

" visual studio only supports split horiozntal
" map <Leader>sv :vsc Window.SplitWindowVertically<CR>
" map <Leader>sh :vsc Window.SplitWindowHorizontally<CR>
"
" only way to split horizontally
map <Leader>sh :vsc Window.Split<CR>
map <C-j> :vsc Window.NextSplitPane<CR>

" control + k doesn't work
" map <C-k> :vsc Window.NextSplitPane<CR>



" turn off highlight search
map <Leader>nh :nohl<cr>

" like nvim-tree
nnoremap <C-n> :vsc View.SolutionExplorer<CR>

" utils, shortcut to open visual studio options
nnoremap <C-,> :vsc Tools.Options<CR>

" Search, equivalent to telescope
nnoremap <Leader>ff :vsc Edit.GoToAll<CR>

" LSP Oriented Settings
nnoremap gD :vsc Edit.GoToDeclaration<CR>
nnoremap gd :vsc Edit.GoToDefinition<CR>
nnoremap K :vsc Edit.PeekDefinition<CR>
nnoremap gr :vsc Edit.FindAllReferences<CR>
nnoremap gi :vsc Edit.GoToImplementation<CR>
