#!/bin/bash
# Symlink the Hyprland / CachyOS desktop configs from this repo into ~/.config.
# Mirrors scripts/linux-symlink.sh (Debian/Sway) for the CachyOS/Hyprland box.
# Existing real files/dirs are backed up to <name>.bak.<timestamp> first, so it
# is safe to re-run.

set -euo pipefail

dotfiles="${HOME}/Workspace/dotfiles"

backup() {  # backup <dest> if it exists and is not already a symlink
  local dest="$1"
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    mv "$dest" "${dest}.bak.$(date +%s)"
    echo "  backed up $dest"
  fi
}

link() {  # link <src-relative-to-dotfiles> <dest-absolute>
  local src="${dotfiles}/$1" dest="$2"
  mkdir -p "$(dirname "$dest")"
  backup "$dest"
  ln -sfn "$src" "$dest"
  echo "  linked $dest -> $src"
}

echo "Linking Hyprland desktop configs..."

# Whole-directory configs
link config/hypr   "${HOME}/.config/hypr"
link config/wofi   "${HOME}/.config/wofi"
link config/swaync "${HOME}/.config/swaync"

# Waybar: shared style + the hyprland-specific config file
mkdir -p "${HOME}/.config/waybar"
link config/waybar/style.css       "${HOME}/.config/waybar/style.css"
link config/waybar/config-hyprland "${HOME}/.config/waybar/config"

# Fish shell
link config/fish/config.fish "${HOME}/.config/fish/config.fish"

# Qt theming (dolphin)
link config/qt/qt5ct.conf "${HOME}/.config/qt5ct/qt5ct.conf"
link config/qt/qt6ct.conf "${HOME}/.config/qt6ct/qt6ct.conf"

# Kitty: whole config dir (brings themes/), then per-OS file -> kitty.conf
link config/kitty "${HOME}/.config/kitty"
ln -sfn "${HOME}/.config/kitty/kitty-linux.conf" "${HOME}/.config/kitty/kitty.conf"

# Starship prompt config (generated by the installer: starship preset tokyo-night)
if [ -f "${dotfiles}/config/starship.toml" ]; then
  link config/starship.toml "${HOME}/.config/starship.toml"
fi

echo "Done. Apply with: hyprctl reload"
